### ISSUE TITLE
Windows binary flags virus scan,  does not run

### ISSUE THREAD

**Issue by vongoh** [facelessuser/ColorSchemeEditor#14] opened 2015-04-28 02:54 UTC
I ran your Windows binary.   Downloaded, doubleclicked to run, and got a message from  BitDefender that it was 'disinfecting a file'.

A moment later BitDefender informed me that "A potentially malicious program tried to run.  Allow and monitor or quarantine"?

Since I've seen you around these parts on other projects, I decided to trust you and just allow and monitor.   Then the interface never came up.

Have you run into this  before?

**Comment by facelessuser** [comment] 2015-04-28 03:10
If you have any doubts, the source code is here: https://github.com/facelessuser/ColorSchemeEditor/tree/GUI_Source.

The problem is probably because I use [PyInstaller](https://github.com/pyinstaller/pyinstaller) to bundle it as an exe.  There have been antivirus in the past that have flagged pyinstaller bundles as viruses, but they are not.

I had this happen at work I think once with trendmicro.  Maybe building the app with a new version of Pyinstaller would help.  I haven't re-built it in a while.

**Comment by facelessuser** [comment] 2015-05-03 03:44
As this is really a false positive from the antivirus, I am going to close this.  Sometime in the future, I will try and build and release it a new version with a newer PyInstaller, but priority is pretty low, and there is no guarantee it would even fix the issue as it just may be that the antivirus rules need to be tweaked by that vendor.

**Closed by facelessuser** 2015-05-03 03:44 UTC

**Comment by facelessuser** [comment] 2015-05-23 00:56
FYI, GUI has been moved here: https://github.com/facelessuser/subclrschm.  It should now be installable without using PyInstaller...Assuming you have wxPython 2.9.4 installed (one of these days I plan on supporting later versions).  If you have a later version of wxPython, they should be able to exist side by side, and this tool should properly import the one needed.

```
python setup.py build
python setup.py install
```

Anyways, you might have moved on from this, but for anyone searching in the future this might be useful.
